volumes:
  dvwa:


networks:
  dvwa:


services:
  dvwa:
    build: .
    image: vulnerables/dvwa:latest
    # Change `always` to `build` to build from local source
    container_name: dvwa
    pull_policy: always
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    # Uncomment the next 2 lines to serve local source
    volumes:
      - ./:/var/www/html
    networks:
      - dvwa
    ports:
      - "8081:80"
    restart: always

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped
